[tools]
aube = "latest"
biome = "latest"
pitchfork = "latest"
pnpm = "latest"
prek = "latest"

[tasks.dev]
description = "Arranca el servidor dev"
run = "aube dev"

[tasks.lint]
description = "Lintea los archivos"
run = "biome lint ."
